name: Sync GitHub → Hugging Face Space
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Sync to Hugging Face Space
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: pranit144/MediCare
          huggingface_repo_id: pranit144/pranit144
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
          space_sdk: gradio  # use 'streamlit' or 'static' if appropriate
          private: false
